### ISSUE TITLE
usb_open() failed, windows multiple device bug

### ISSUE THREAD

**Issue by RyanHope** [codedstructure/pylibftdi.old#1]
I think I have found a bug with this library on Windows. I have 2 ftdi devices plugged into a test machine right now. One has libusbk configured as its driver the other one does not. If I try and open a device by its serial number I get a usb_open() error. If I unplug the device without the libusbk driver I can open the device no problem.

**Comment by vstadnytskyi** [comment]
What is the solution to this problem?
